FROM almalinux:9
RUN dnf install nginx -y







# RUN command executes only at image build time, not at runtime(after image creation)
#  RUN commands can be used to install packages, copy files, etc.  
# any number of RUN commands can be used in a Dockerfile
# RUN commands are executed in the order they appear in the Dockerfile